# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad547459d4e11c3f9f09dae2d3ebe6ec"
name = "PrescriptionDetails"
handle = "prescriptiondetails"
application_url = "https://firm-walk-char-grateful.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://firm-walk-char-grateful.trycloudflare.com/auth/callback", "https://firm-walk-char-grateful.trycloudflare.com/auth/shopify/callback", "https://firm-walk-char-grateful.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
